# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PublicKey(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, public_keyname: str=None, company_id: str=None, agent_id: str=None, jwk: object=None):  # noqa: E501
        """PublicKey - a model defined in Swagger

        :param id: The id of this PublicKey.  # noqa: E501
        :type id: str
        :param public_keyname: The public_keyname of this PublicKey.  # noqa: E501
        :type public_keyname: str
        :param company_id: The company_id of this PublicKey.  # noqa: E501
        :type company_id: str
        :param agent_id: The agent_id of this PublicKey.  # noqa: E501
        :type agent_id: str
        :param jwk: The jwk of this PublicKey.  # noqa: E501
        :type jwk: object
        """
        self.swagger_types = {
            'id': str,
            'public_keyname': str,
            'company_id': str,
            'agent_id': str,
            'jwk': object
        }

        self.attribute_map = {
            'id': 'id',
            'public_keyname': 'publicKeyname',
            'company_id': 'companyId',
            'agent_id': 'agentId',
            'jwk': 'jwk'
        }

        self._id = id
        self._public_keyname = public_keyname
        self._company_id = company_id
        self._agent_id = agent_id
        self._jwk = jwk

    @classmethod
    def from_dict(cls, dikt) -> 'PublicKey':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PublicKey of this PublicKey.  # noqa: E501
        :rtype: PublicKey
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this PublicKey.


        :return: The id of this PublicKey.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this PublicKey.


        :param id: The id of this PublicKey.
        :type id: str
        """

        self._id = id

    @property
    def public_keyname(self) -> str:
        """Gets the public_keyname of this PublicKey.


        :return: The public_keyname of this PublicKey.
        :rtype: str
        """
        return self._public_keyname

    @public_keyname.setter
    def public_keyname(self, public_keyname: str):
        """Sets the public_keyname of this PublicKey.


        :param public_keyname: The public_keyname of this PublicKey.
        :type public_keyname: str
        """

        self._public_keyname = public_keyname

    @property
    def company_id(self) -> str:
        """Gets the company_id of this PublicKey.


        :return: The company_id of this PublicKey.
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id: str):
        """Sets the company_id of this PublicKey.


        :param company_id: The company_id of this PublicKey.
        :type company_id: str
        """

        self._company_id = company_id

    @property
    def agent_id(self) -> str:
        """Gets the agent_id of this PublicKey.


        :return: The agent_id of this PublicKey.
        :rtype: str
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id: str):
        """Sets the agent_id of this PublicKey.


        :param agent_id: The agent_id of this PublicKey.
        :type agent_id: str
        """

        self._agent_id = agent_id

    @property
    def jwk(self) -> object:
        """Gets the jwk of this PublicKey.

        JSON Web Key representation of public key.  # noqa: E501

        :return: The jwk of this PublicKey.
        :rtype: object
        """
        return self._jwk

    @jwk.setter
    def jwk(self, jwk: object):
        """Sets the jwk of this PublicKey.

        JSON Web Key representation of public key.  # noqa: E501

        :param jwk: The jwk of this PublicKey.
        :type jwk: object
        """

        self._jwk = jwk
